### ISSUE TITLE
Deserialization issue compatibilityMode

### ISSUE THREAD

**Issue by fredlange** [wendigo/chrome-reactive-kotlin#61]
Partial stacktrace when deserializing `Node`.

`
kotlinx.serialization.json.internal.JsonDecodingException: Encountered unknown key 'compatibilityMode'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
Current input: .....le.com/","xmlVersion":"","compatibilityMode":"NoQuirksMode"}
at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
at pl.wendigo.chrome.api.dom.Node$$serializer.deserialize(Types.kt)
at pl.wendigo.chrome.api.dom.Node$$serializer.deserialize(Types.kt:134)
at pl.wendigo.chrome.api.dom.GetDocumentResponse$$serializer.deserialize(Domain.kt)
at pl.wendigo.chrome.api.dom.GetDocumentResponse$$serializer.deserialize(Domain.kt:862)
at pl.wendigo.chrome.protocol.websocket.FrameMapper.deserializeResponseFrame$chrome_reactive_kotlin(FrameMapper.kt:39)
at pl.wendigo.chrome.protocol.websocket.WebSocketFramesStream$getResponse$2.apply(WebSocketFramesStream.kt:66)
at pl.wendigo.chrome.protocol.websocket.WebSocketFramesStream$getResponse$2.apply(WebSocketFramesStream.kt:28)
`

Maybe https://github.com/wendigo/chrome-reactive-kotlin/blob/master/src/main/kotlin/pl/wendigo/chrome/protocol/websocket/FrameMapper.kt#L39 needs to be relaxed as well?

**Comment by ssoper** [comment]
bump, seeing this as well, any plans to resolve or short term workarounds? thanks
